package sic

// validCodes contains the SIC records published by the U.S. Securities and Exchange Commission.
var validCodes = map[Code]struct{}{
	{Code: "100", Office: "Industrial Applications and Services", IndustryTitle: "AGRICULTURAL PRODUCTION-CROPS"}:                                  {},
	{Code: "200", Office: "Industrial Applications and Services", IndustryTitle: "AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES"}:               {},
	{Code: "700", Office: "Industrial Applications and Services", IndustryTitle: "AGRICULTURAL SERVICES"}:                                          {},
	{Code: "800", Office: "Industrial Applications and Services", IndustryTitle: "FORESTRY"}:                                                       {},
	{Code: "900", Office: "Industrial Applications and Services", IndustryTitle: "FISHING, HUNTING AND TRAPPING"}:                                  {},
	{Code: "1000", Office: "Office of Energy & Transportation", IndustryTitle: "METAL MINING"}:                                                     {},
	{Code: "1040", Office: "Office of Energy & Transportation", IndustryTitle: "GOLD AND SILVER ORES"}:                                             {},
	{Code: "1090", Office: "Office of Energy & Transportation", IndustryTitle: "MISCELLANEOUS METAL ORES"}:                                         {},
	{Code: "1220", Office: "Office of Energy & Transportation", IndustryTitle: "BITUMINOUS COAL & LIGNITE MINING"}:                                 {},
	{Code: "1221", Office: "Office of Energy & Transportation", IndustryTitle: "BITUMINOUS COAL & LIGNITE SURFACE MINING"}:                         {},
	{Code: "1311", Office: "Office of Energy & Transportation", IndustryTitle: "CRUDE PETROLEUM & NATURAL GAS"}:                                    {},
	{Code: "1381", Office: "Office of Energy & Transportation", IndustryTitle: "DRILLING OIL & GAS WELLS"}:                                         {},
	{Code: "1382", Office: "Office of Energy & Transportation", IndustryTitle: "OIL & GAS FIELD EXPLORATION SERVICES"}:                             {},
	{Code: "1389", Office: "Office of Energy & Transportation", IndustryTitle: "OIL & GAS FIELD SERVICES, NEC"}:                                    {},
	{Code: "1400", Office: "Office of Energy & Transportation", IndustryTitle: "MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)"}:            {},
	{Code: "1520", Office: "Office of Real Estate & Construction", IndustryTitle: "GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS"}:                  {},
	{Code: "1531", Office: "Office of Real Estate & Construction", IndustryTitle: "OPERATIVE BUILDERS"}:                                            {},
	{Code: "1540", Office: "Office of Real Estate & Construction", IndustryTitle: "GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS"}:               {},
	{Code: "1600", Office: "Office of Real Estate & Construction", IndustryTitle: "HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS"}:        {},
	{Code: "1623", Office: "Office of Real Estate & Construction", IndustryTitle: "WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION"}:        {},
	{Code: "1700", Office: "Office of Real Estate & Construction", IndustryTitle: "CONSTRUCTION - SPECIAL TRADE CONTRACTORS"}:                      {},
	{Code: "1731", Office: "Office of Real Estate & Construction", IndustryTitle: "ELECTRICAL WORK"}:                                               {},
	{Code: "2000", Office: "Office of Manufacturing", IndustryTitle: "FOOD AND KINDRED PRODUCTS"}:                                                  {},
	{Code: "2011", Office: "Office of Manufacturing", IndustryTitle: "MEAT PACKING PLANTS"}:                                                        {},
	{Code: "2013", Office: "Office of Manufacturing", IndustryTitle: "SAUSAGES & OTHER PREPARED MEAT PRODUCTS"}:                                    {},
	{Code: "2015", Office: "Office of Manufacturing", IndustryTitle: "POULTRY SLAUGHTERING AND PROCESSING"}:                                        {},
	{Code: "2020", Office: "Office of Manufacturing", IndustryTitle: "DAIRY PRODUCTS"}:                                                             {},
	{Code: "2024", Office: "Office of Manufacturing", IndustryTitle: "ICE CREAM & FROZEN DESSERTS"}:                                                {},
	{Code: "2030", Office: "Office of Manufacturing", IndustryTitle: "CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES"}:                    {},
	{Code: "2033", Office: "Office of Manufacturing", IndustryTitle: "CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES"}:                             {},
	{Code: "2040", Office: "Office of Manufacturing", IndustryTitle: "GRAIN MILL PRODUCTS"}:                                                        {},
	{Code: "2050", Office: "Office of Manufacturing", IndustryTitle: "BAKERY PRODUCTS"}:                                                            {},
	{Code: "2052", Office: "Office of Manufacturing", IndustryTitle: "COOKIES & CRACKERS"}:                                                         {},
	{Code: "2060", Office: "Office of Manufacturing", IndustryTitle: "SUGAR & CONFECTIONERY PRODUCTS"}:                                             {},
	{Code: "2070", Office: "Office of Manufacturing", IndustryTitle: "FATS & OILS"}:                                                                {},
	{Code: "2080", Office: "Office of Manufacturing", IndustryTitle: "BEVERAGES"}:                                                                  {},
	{Code: "2082", Office: "Office of Manufacturing", IndustryTitle: "MALT BEVERAGES"}:                                                             {},
	{Code: "2086", Office: "Office of Manufacturing", IndustryTitle: "BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS"}:                           {},
	{Code: "2090", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS"}:                         {},
	{Code: "2092", Office: "Office of Manufacturing", IndustryTitle: "PREPARED FRESH OR FROZEN FISH & SEAFOODS"}:                                   {},
	{Code: "2100", Office: "Office of Manufacturing", IndustryTitle: "TOBACCO PRODUCTS"}:                                                           {},
	{Code: "2111", Office: "Office of Manufacturing", IndustryTitle: "CIGARETTES"}:                                                                 {},
	{Code: "2200", Office: "Office of Manufacturing", IndustryTitle: "TEXTILE MILL PRODUCTS"}:                                                      {},
	{Code: "2211", Office: "Office of Manufacturing", IndustryTitle: "BROADWOVEN FABRIC MILLS, COTTON"}:                                            {},
	{Code: "2221", Office: "Office of Manufacturing", IndustryTitle: "BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK"}:                             {},
	{Code: "2250", Office: "Office of Manufacturing", IndustryTitle: "KNITTING MILLS"}:                                                             {},
	{Code: "2253", Office: "Office of Manufacturing", IndustryTitle: "KNIT OUTERWEAR MILLS"}:                                                       {},
	{Code: "2273", Office: "Office of Manufacturing", IndustryTitle: "CARPETS & RUGS"}:                                                             {},
	{Code: "2300", Office: "Office of Manufacturing", IndustryTitle: "APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL"}:                    {},
	{Code: "2320", Office: "Office of Manufacturing", IndustryTitle: "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS"}:                    {},
	{Code: "2330", Office: "Office of Manufacturing", IndustryTitle: "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR"}:                                    {},
	{Code: "2340", Office: "Office of Manufacturing", IndustryTitle: "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS"}:                      {},
	{Code: "2390", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS FABRICATED TEXTILE PRODUCTS"}:                                  {},
	{Code: "2400", Office: "Office of Manufacturing", IndustryTitle: "LUMBER & WOOD PRODUCTS (NO FURNITURE)"}:                                      {},
	{Code: "2421", Office: "Office of Manufacturing", IndustryTitle: "SAWMILLS & PLANTING MILLS, GENERAL"}:                                         {},
	{Code: "2430", Office: "Office of Manufacturing", IndustryTitle: "MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS"}:                       {},
	{Code: "2451", Office: "Office of Manufacturing", IndustryTitle: "MOBILE HOMES"}:                                                               {},
	{Code: "2452", Office: "Office of Manufacturing", IndustryTitle: "PREFABRICATED WOOD BLDGS & COMPONENTS"}:                                      {},
	{Code: "2510", Office: "Office of Manufacturing", IndustryTitle: "HOUSEHOLD FURNITURE"}:                                                        {},
	{Code: "2511", Office: "Office of Manufacturing", IndustryTitle: "WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)"}:                                 {},
	{Code: "2520", Office: "Office of Manufacturing", IndustryTitle: "OFFICE FURNITURE"}:                                                           {},
	{Code: "2522", Office: "Office of Manufacturing", IndustryTitle: "OFFICE FURNITURE (NO WOOD)"}:                                                 {},
	{Code: "2531", Office: "Office of Manufacturing", IndustryTitle: "PUBLIC BLDG & RELATED FURNITURE"}:                                            {},
	{Code: "2540", Office: "Office of Manufacturing", IndustryTitle: "PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES"}:                     {},
	{Code: "2590", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS FURNITURE & FIXTURES"}:                                         {},
	{Code: "2600", Office: "Office of Manufacturing", IndustryTitle: "PAPERS & ALLIED PRODUCTS"}:                                                   {},
	{Code: "2611", Office: "Office of Manufacturing", IndustryTitle: "PULP MILLS"}:                                                                 {},
	{Code: "2621", Office: "Office of Manufacturing", IndustryTitle: "PAPER MILLS"}:                                                                {},
	{Code: "2631", Office: "Office of Manufacturing", IndustryTitle: "PAPERBOARD MILLS"}:                                                           {},
	{Code: "2650", Office: "Office of Manufacturing", IndustryTitle: "PAPERBOARD CONTAINERS & BOXES"}:                                              {},
	{Code: "2670", Office: "Office of Manufacturing", IndustryTitle: "CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)"}:                    {},
	{Code: "2673", Office: "Office of Manufacturing", IndustryTitle: "PLASTICS, FOIL & COATED PAPER BAGS"}:                                         {},
	{Code: "2711", Office: "Office of Manufacturing", IndustryTitle: "NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING"}:                            {},
	{Code: "2721", Office: "Office of Manufacturing", IndustryTitle: "PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING"}:                           {},
	{Code: "2731", Office: "Office of Manufacturing", IndustryTitle: "BOOKS: PUBLISHING OR PUBLISHING & PRINTING"}:                                 {},
	{Code: "2732", Office: "Office of Manufacturing", IndustryTitle: "BOOK PRINTING"}:                                                              {},
	{Code: "2741", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS PUBLISHING"}:                                                   {},
	{Code: "2750", Office: "Office of Manufacturing", IndustryTitle: "COMMERCIAL PRINTING"}:                                                        {},
	{Code: "2761", Office: "Office of Manufacturing", IndustryTitle: "MANIFOLD BUSINESS FORMS"}:                                                    {},
	{Code: "2771", Office: "Office of Manufacturing", IndustryTitle: "GREETING CARDS"}:                                                             {},
	{Code: "2780", Office: "Office of Manufacturing", IndustryTitle: "BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK"}:                    {},
	{Code: "2790", Office: "Office of Manufacturing", IndustryTitle: "SERVICE INDUSTRIES FOR THE PRINTING TRADE"}:                                  {},
	{Code: "2800", Office: "Industrial Applications and Services", IndustryTitle: "CHEMICALS & ALLIED PRODUCTS"}:                                   {},
	{Code: "2810", Office: "Industrial Applications and Services", IndustryTitle: "INDUSTRIAL INORGANIC CHEMICALS"}:                                {},
	{Code: "2820", Office: "Industrial Applications and Services", IndustryTitle: "PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)"}:     {},
	{Code: "2821", Office: "Industrial Applications and Services", IndustryTitle: "PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS"}:        {},
	{Code: "2833", Office: "Office of Life Sciences", IndustryTitle: "MEDICINAL CHEMICALS & BOTANICAL PRODUCTS"}:                                   {},
	{Code: "2834", Office: "Office of Life Sciences", IndustryTitle: "PHARMACEUTICAL PREPARATIONS"}:                                                {},
	{Code: "2835", Office: "Office of Life Sciences", IndustryTitle: "IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES"}:                                   {},
	{Code: "2836", Office: "Office of Life Sciences", IndustryTitle: "BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)"}:                            {},
	{Code: "2840", Office: "Industrial Applications and Services", IndustryTitle: "SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS"}:    {},
	{Code: "2842", Office: "Industrial Applications and Services", IndustryTitle: "SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS"}:     {},
	{Code: "2844", Office: "Industrial Applications and Services", IndustryTitle: "PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS"}:               {},
	{Code: "2851", Office: "Industrial Applications and Services", IndustryTitle: "PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS"}:           {},
	{Code: "2860", Office: "Industrial Applications and Services", IndustryTitle: "INDUSTRIAL ORGANIC CHEMICALS"}:                                  {},
	{Code: "2870", Office: "Industrial Applications and Services", IndustryTitle: "AGRICULTURAL CHEMICALS"}:                                        {},
	{Code: "2890", Office: "Industrial Applications and Services", IndustryTitle: "MISCELLANEOUS CHEMICAL PRODUCTS"}:                               {},
	{Code: "2891", Office: "Industrial Applications and Services", IndustryTitle: "ADHESIVES & SEALANTS"}:                                          {},
	{Code: "2911", Office: "Office of Energy & Transportation", IndustryTitle: "PETROLEUM REFINING"}:                                               {},
	{Code: "2950", Office: "Office of Energy & Transportation", IndustryTitle: "ASPHALT PAVING & ROOFING MATERIALS"}:                               {},
	{Code: "2990", Office: "Office of Energy & Transportation", IndustryTitle: "MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL"}:                       {},
	{Code: "3011", Office: "Office of Manufacturing", IndustryTitle: "TIRES & INNER TUBES"}:                                                        {},
	{Code: "3021", Office: "Office of Manufacturing", IndustryTitle: "RUBBER & PLASTICS FOOTWEAR"}:                                                 {},
	{Code: "3050", Office: "Office of Manufacturing", IndustryTitle: "GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE"}:                    {},
	{Code: "3060", Office: "Office of Manufacturing", IndustryTitle: "FABRICATED RUBBER PRODUCTS, NEC"}:                                            {},
	{Code: "3080", Office: "Industrial Applications and Services", IndustryTitle: "MISCELLANEOUS PLASTICS PRODUCTS"}:                               {},
	{Code: "3081", Office: "Industrial Applications and Services", IndustryTitle: "UNSUPPORTED PLASTICS FILM & SHEET"}:                             {},
	{Code: "3086", Office: "Industrial Applications and Services", IndustryTitle: "PLASTICS FOAM PRODUCTS"}:                                        {},
	{Code: "3089", Office: "Industrial Applications and Services", IndustryTitle: "PLASTICS PRODUCTS, NEC"}:                                        {},
	{Code: "3100", Office: "Office of Manufacturing", IndustryTitle: "LEATHER & LEATHER PRODUCTS"}:                                                 {},
	{Code: "3140", Office: "Office of Manufacturing", IndustryTitle: "FOOTWEAR, (NO RUBBER)"}:                                                      {},
	{Code: "3211", Office: "Office of Manufacturing", IndustryTitle: "FLAT GLASS"}:                                                                 {},
	{Code: "3220", Office: "Office of Manufacturing", IndustryTitle: "GLASS & GLASSWARE, PRESSED OR BLOWN"}:                                        {},
	{Code: "3221", Office: "Office of Manufacturing", IndustryTitle: "GLASS CONTAINERS"}:                                                           {},
	{Code: "3231", Office: "Office of Manufacturing", IndustryTitle: "GLASS PRODUCTS, MADE OF PURCHASED GLASS"}:                                    {},
	{Code: "3241", Office: "Office of Manufacturing", IndustryTitle: "CEMENT, HYDRAULIC"}:                                                          {},
	{Code: "3250", Office: "Office of Manufacturing", IndustryTitle: "STRUCTURAL CLAY PRODUCTS"}:                                                   {},
	{Code: "3260", Office: "Office of Manufacturing", IndustryTitle: "POTTERY & RELATED PRODUCTS"}:                                                 {},
	{Code: "3270", Office: "Office of Manufacturing", IndustryTitle: "CONCRETE, GYPSUM & PLASTER PRODUCTS"}:                                        {},
	{Code: "3272", Office: "Office of Manufacturing", IndustryTitle: "CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK"}:                                    {},
	{Code: "3281", Office: "Office of Manufacturing", IndustryTitle: "CUT STONE & STONE PRODUCTS"}:                                                 {},
	{Code: "3290", Office: "Office of Manufacturing", IndustryTitle: "ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS"}:                        {},
	{Code: "3310", Office: "Office of Manufacturing", IndustryTitle: "STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS"}:                    {},
	{Code: "3312", Office: "Office of Manufacturing", IndustryTitle: "STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)"}:                   {},
	{Code: "3317", Office: "Office of Manufacturing", IndustryTitle: "STEEL PIPE & TUBES"}:                                                         {},
	{Code: "3320", Office: "Office of Manufacturing", IndustryTitle: "IRON & STEEL FOUNDRIES"}:                                                     {},
	{Code: "3330", Office: "Office of Manufacturing", IndustryTitle: "PRIMARY SMELTING & REFINING OF NONFERROUS METALS"}:                           {},
	{Code: "3334", Office: "Office of Manufacturing", IndustryTitle: "PRIMARY PRODUCTION OF ALUMINUM"}:                                             {},
	{Code: "3341", Office: "Office of Manufacturing", IndustryTitle: "SECONDARY SMELTING & REFINING OF NONFERROUS METALS"}:                         {},
	{Code: "3350", Office: "Office of Manufacturing", IndustryTitle: "ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS"}:                           {},
	{Code: "3357", Office: "Office of Manufacturing", IndustryTitle: "DRAWING & INSULATING OF NONFERROUS WIRE"}:                                    {},
	{Code: "3360", Office: "Office of Manufacturing", IndustryTitle: "NONFERROUS FOUNDRIES (CASTINGS)"}:                                            {},
	{Code: "3390", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS PRIMARY METAL PRODUCTS"}:                                       {},
	{Code: "3411", Office: "Office of Manufacturing", IndustryTitle: "METAL CANS"}:                                                                 {},
	{Code: "3412", Office: "Office of Manufacturing", IndustryTitle: "METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS"}:                                {},
	{Code: "3420", Office: "Office of Manufacturing", IndustryTitle: "CUTLERY, HANDTOOLS & GENERAL HARDWARE"}:                                      {},
	{Code: "3430", Office: "Office of Manufacturing", IndustryTitle: "HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES"}:                 {},
	{Code: "3433", Office: "Office of Manufacturing", IndustryTitle: "HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES"}:                     {},
	{Code: "3440", Office: "Office of Manufacturing", IndustryTitle: "FABRICATED STRUCTURAL METAL PRODUCTS"}:                                       {},
	{Code: "3442", Office: "Office of Manufacturing", IndustryTitle: "METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM"}:                                 {},
	{Code: "3443", Office: "Office of Manufacturing", IndustryTitle: "FABRICATED PLATE WORK (BOILER SHOPS)"}:                                       {},
	{Code: "3444", Office: "Office of Manufacturing", IndustryTitle: "SHEET METAL WORK"}:                                                           {},
	{Code: "3448", Office: "Office of Manufacturing", IndustryTitle: "PREFABRICATED METAL BUILDINGS & COMPONENTS"}:                                 {},
	{Code: "3451", Office: "Office of Manufacturing", IndustryTitle: "SCREW MACHINE PRODUCTS"}:                                                     {},
	{Code: "3452", Office: "Office of Manufacturing", IndustryTitle: "BOLTS, NUTS, SCREWS, RIVETS & WASHERS"}:                                      {},
	{Code: "3460", Office: "Office of Manufacturing", IndustryTitle: "METAL FORGINGS & STAMPINGS"}:                                                 {},
	{Code: "3470", Office: "Office of Manufacturing", IndustryTitle: "COATING, ENGRAVING & ALLIED SERVICES"}:                                       {},
	{Code: "3480", Office: "Office of Manufacturing", IndustryTitle: "ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)"}:                      {},
	{Code: "3490", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS FABRICATED METAL PRODUCTS"}:                                    {},
	{Code: "3510", Office: "Office of Technology", IndustryTitle: "ENGINES & TURBINES"}:                                                            {},
	{Code: "3523", Office: "Office of Technology", IndustryTitle: "FARM MACHINERY & EQUIPMENT"}:                                                    {},
	{Code: "3524", Office: "Office of Technology", IndustryTitle: "LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP"}:                            {},
	{Code: "3530", Office: "Office of Technology", IndustryTitle: "CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP"}:                   {},
	{Code: "3531", Office: "Office of Technology", IndustryTitle: "CONSTRUCTION MACHINERY & EQUIP"}:                                                {},
	{Code: "3532", Office: "Office of Technology", IndustryTitle: "MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)"}:                    {},
	{Code: "3533", Office: "Office of Energy & Transportation", IndustryTitle: "OIL & GAS FIELD MACHINERY & EQUIPMENT"}:                            {},
	{Code: "3537", Office: "Office of Technology", IndustryTitle: "INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS"}:                              {},
	{Code: "3540", Office: "Office of Technology", IndustryTitle: "METALWORKG MACHINERY & EQUIPMENT"}:                                              {},
	{Code: "3541", Office: "Office of Technology", IndustryTitle: "MACHINE TOOLS, METAL CUTTING TYPES"}:                                            {},
	{Code: "3550", Office: "Office of Technology", IndustryTitle: "SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)"}:                        {},
	{Code: "3555", Office: "Office of Technology", IndustryTitle: "PRINTING TRADES MACHINERY & EQUIPMENT"}:                                         {},
	{Code: "3559", Office: "Office of Technology", IndustryTitle: "SPECIAL INDUSTRY MACHINERY, NEC"}:                                               {},
	{Code: "3560", Office: "Office of Technology", IndustryTitle: "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT"}:                                      {},
	{Code: "3561", Office: "Office of Technology", IndustryTitle: "PUMPS & PUMPING EQUIPMENT"}:                                                     {},
	{Code: "3562", Office: "Office of Technology", IndustryTitle: "BALL & ROLLER BEARINGS"}:                                                        {},
	{Code: "3564", Office: "Office of Technology", IndustryTitle: "INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP"}:                   {},
	{Code: "3567", Office: "Office of Technology", IndustryTitle: "INDUSTRIAL PROCESS FURNACES & OVENS"}:                                           {},
	{Code: "3569", Office: "Office of Technology", IndustryTitle: "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC"}:                                 {},
	{Code: "3570", Office: "Office of Technology", IndustryTitle: "COMPUTER & OFFICE EQUIPMENT"}:                                                   {},
	{Code: "3571", Office: "Office of Technology", IndustryTitle: "ELECTRONIC COMPUTERS"}:                                                          {},
	{Code: "3572", Office: "Office of Technology", IndustryTitle: "COMPUTER STORAGE DEVICES"}:                                                      {},
	{Code: "3575", Office: "Office of Technology", IndustryTitle: "COMPUTER TERMINALS"}:                                                            {},
	{Code: "3576", Office: "Office of Technology", IndustryTitle: "COMPUTER COMMUNICATIONS EQUIPMENT"}:                                             {},
	{Code: "3577", Office: "Office of Technology", IndustryTitle: "COMPUTER PERIPHERAL EQUIPMENT, NEC"}:                                            {},
	{Code: "3578", Office: "Office of Technology", IndustryTitle: "CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)"}:                   {},
	{Code: "3579", Office: "Office of Technology", IndustryTitle: "OFFICE MACHINES, NEC"}:                                                          {},
	{Code: "3580", Office: "Office of Technology", IndustryTitle: "REFRIGERATION & SERVICE INDUSTRY MACHINERY"}:                                    {},
	{Code: "3585", Office: "Office of Technology", IndustryTitle: "AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP"}:                    {},
	{Code: "3590", Office: "Office of Technology", IndustryTitle: "MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT"}:                            {},
	{Code: "3600", Office: "Office of Manufacturing", IndustryTitle: "ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)"}:                {},
	{Code: "3612", Office: "Office of Manufacturing", IndustryTitle: "POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS"}:                               {},
	{Code: "3613", Office: "Office of Manufacturing", IndustryTitle: "SWITCHGEAR & SWITCHBOARD APPARATUS"}:                                         {},
	{Code: "3620", Office: "Office of Manufacturing", IndustryTitle: "ELECTRICAL INDUSTRIAL APPARATUS"}:                                            {},
	{Code: "3621", Office: "Office of Manufacturing", IndustryTitle: "MOTORS & GENERATORS"}:                                                        {},
	{Code: "3630", Office: "Office of Manufacturing", IndustryTitle: "HOUSEHOLD APPLIANCES"}:                                                       {},
	{Code: "3634", Office: "Office of Manufacturing", IndustryTitle: "ELECTRIC HOUSEWARES & FANS"}:                                                 {},
	{Code: "3640", Office: "Office of Manufacturing", IndustryTitle: "ELECTRIC LIGHTING & WIRING EQUIPMENT"}:                                       {},
	{Code: "3651", Office: "Office of Manufacturing", IndustryTitle: "HOUSEHOLD AUDIO & VIDEO EQUIPMENT"}:                                          {},
	{Code: "3652", Office: "Office of Manufacturing", IndustryTitle: "PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS"}:                       {},
	{Code: "3661", Office: "Office of Manufacturing", IndustryTitle: "TELEPHONE & TELEGRAPH APPARATUS"}:                                            {},
	{Code: "3663", Office: "Office of Manufacturing", IndustryTitle: "RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT"}:                         {},
	{Code: "3669", Office: "Office of Manufacturing", IndustryTitle: "COMMUNICATIONS EQUIPMENT, NEC"}:                                              {},
	{Code: "3670", Office: "Office of Manufacturing", IndustryTitle: "ELECTRONIC COMPONENTS & ACCESSORIES"}:                                        {},
	{Code: "3672", Office: "Office of Manufacturing", IndustryTitle: "PRINTED CIRCUIT BOARDS"}:                                                     {},
	{Code: "3674", Office: "Office of Manufacturing", IndustryTitle: "SEMICONDUCTORS & RELATED DEVICES"}:                                           {},
	{Code: "3677", Office: "Office of Manufacturing", IndustryTitle: "ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS"}:                           {},
	{Code: "3678", Office: "Office of Manufacturing", IndustryTitle: "ELECTRONIC CONNECTORS"}:                                                      {},
	{Code: "3679", Office: "Office of Manufacturing", IndustryTitle: "ELECTRONIC COMPONENTS, NEC"}:                                                 {},
	{Code: "3690", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES"}:                   {},
	{Code: "3695", Office: "Office of Manufacturing", IndustryTitle: "MAGNETIC & OPTICAL RECORDING MEDIA"}:                                         {},
	{Code: "3711", Office: "Office of Manufacturing", IndustryTitle: "MOTOR VEHICLES & PASSENGER CAR BODIES"}:                                      {},
	{Code: "3713", Office: "Office of Manufacturing", IndustryTitle: "TRUCK & BUS BODIES"}:                                                         {},
	{Code: "3714", Office: "Office of Manufacturing", IndustryTitle: "MOTOR VEHICLE PARTS & ACCESSORIES"}:                                          {},
	{Code: "3715", Office: "Office of Manufacturing", IndustryTitle: "TRUCK TRAILERS"}:                                                             {},
	{Code: "3716", Office: "Office of Manufacturing", IndustryTitle: "MOTOR HOMES"}:                                                                {},
	{Code: "3720", Office: "Office of Manufacturing", IndustryTitle: "AIRCRAFT & PARTS"}:                                                           {},
	{Code: "3721", Office: "Office of Manufacturing", IndustryTitle: "AIRCRAFT"}:                                                                   {},
	{Code: "3724", Office: "Office of Manufacturing", IndustryTitle: "AIRCRAFT ENGINES & ENGINE PARTS"}:                                            {},
	{Code: "3728", Office: "Office of Manufacturing", IndustryTitle: "AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC"}:                                  {},
	{Code: "3730", Office: "Office of Manufacturing", IndustryTitle: "SHIP & BOAT BUILDING & REPAIRING"}:                                           {},
	{Code: "3743", Office: "Office of Manufacturing", IndustryTitle: "RAILROAD EQUIPMENT"}:                                                         {},
	{Code: "3751", Office: "Office of Manufacturing", IndustryTitle: "MOTORCYCLES, BICYCLES & PARTS"}:                                              {},
	{Code: "3760", Office: "Office of Manufacturing", IndustryTitle: "GUIDED MISSILES & SPACE VEHICLES & PARTS"}:                                   {},
	{Code: "3790", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS TRANSPORTATION EQUIPMENT"}:                                     {},
	{Code: "3812", Office: "Office of Manufacturing", IndustryTitle: "SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS"}:                  {},
	{Code: "3821", Office: "Industrial Applications and Services", IndustryTitle: "LABORATORY APPARATUS & FURNITURE"}:                              {},
	{Code: "3822", Office: "Industrial Applications and Services", IndustryTitle: "AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS"}: {},
	{Code: "3823", Office: "Industrial Applications and Services", IndustryTitle: "INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL"}:  {},
	{Code: "3824", Office: "Industrial Applications and Services", IndustryTitle: "TOTALIZING FLUID METERS & COUNTING DEVICES"}:                    {},
	{Code: "3825", Office: "Industrial Applications and Services", IndustryTitle: "INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS"}:  {},
	{Code: "3826", Office: "Industrial Applications and Services", IndustryTitle: "LABORATORY ANALYTICAL INSTRUMENTS"}:                             {},
	{Code: "3827", Office: "Industrial Applications and Services", IndustryTitle: "OPTICAL INSTRUMENTS & LENSES"}:                                  {},
	{Code: "3829", Office: "Industrial Applications and Services", IndustryTitle: "MEASURING & CONTROLLING DEVICES, NEC"}:                          {},
	{Code: "3841", Office: "Industrial Applications and Services", IndustryTitle: "SURGICAL & MEDICAL INSTRUMENTS & APPARATUS"}:                    {},
	{Code: "3842", Office: "Industrial Applications and Services", IndustryTitle: "ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES"}:       {},
	{Code: "3843", Office: "Industrial Applications and Services", IndustryTitle: "DENTAL EQUIPMENT & SUPPLIES"}:                                   {},
	{Code: "3844", Office: "Industrial Applications and Services", IndustryTitle: "X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS"}:       {},
	{Code: "3845", Office: "Industrial Applications and Services", IndustryTitle: "ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS"}:                 {},
	{Code: "3851", Office: "Industrial Applications and Services", IndustryTitle: "OPHTHALMIC GOODS"}:                                              {},
	{Code: "3861", Office: "Industrial Applications and Services", IndustryTitle: "PHOTOGRAPHIC EQUIPMENT & SUPPLIES"}:                             {},
	{Code: "3873", Office: "Industrial Applications and Services", IndustryTitle: "WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS"}:             {},
	{Code: "3910", Office: "Office of Manufacturing", IndustryTitle: "JEWELRY, SILVERWARE & PLATED WARE"}:                                          {},
	{Code: "3911", Office: "Office of Manufacturing", IndustryTitle: "JEWELRY, PRECIOUS METAL"}:                                                    {},
	{Code: "3931", Office: "Office of Manufacturing", IndustryTitle: "MUSICAL INSTRUMENTS"}:                                                        {},
	{Code: "3942", Office: "Office of Manufacturing", IndustryTitle: "DOLLS & STUFFED TOYS"}:                                                       {},
	{Code: "3944", Office: "Office of Manufacturing", IndustryTitle: "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)"}:                    {},
	{Code: "3949", Office: "Office of Manufacturing", IndustryTitle: "SPORTING & ATHLETIC GOODS, NEC"}:                                             {},
	{Code: "3950", Office: "Office of Manufacturing", IndustryTitle: "PENS, PENCILS & OTHER ARTISTS' MATERIALS"}:                                   {},
	{Code: "3960", Office: "Office of Manufacturing", IndustryTitle: "COSTUME JEWELRY & NOVELTIES"}:                                                {},
	{Code: "3990", Office: "Office of Manufacturing", IndustryTitle: "MISCELLANEOUS MANUFACTURING INDUSTRIES"}:                                     {},
	{Code: "4011", Office: "Office of Energy & Transportation", IndustryTitle: "RAILROADS, LINE-HAUL OPERATING"}:                                   {},
	{Code: "4013", Office: "Office of Energy & Transportation", IndustryTitle: "RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS"}:                     {},
	{Code: "4100", Office: "Office of Energy & Transportation", IndustryTitle: "LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS"}:        {},
	{Code: "4210", Office: "Office of Energy & Transportation", IndustryTitle: "TRUCKING & COURIER SERVICES (NO AIR)"}:                             {},
	{Code: "4213", Office: "Office of Energy & Transportation", IndustryTitle: "TRUCKING (NO LOCAL)"}:                                              {},
	{Code: "4220", Office: "Office of Energy & Transportation", IndustryTitle: "PUBLIC WAREHOUSING & STORAGE"}:                                     {},
	{Code: "4231", Office: "Office of Energy & Transportation", IndustryTitle: "TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT"}:      {},
	{Code: "4400", Office: "Office of Energy & Transportation", IndustryTitle: "WATER TRANSPORTATION"}:                                             {},
	{Code: "4412", Office: "Office of Energy & Transportation", IndustryTitle: "DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT"}:                       {},
	{Code: "4512", Office: "Office of Energy & Transportation", IndustryTitle: "AIR TRANSPORTATION, SCHEDULED"}:                                    {},
	{Code: "4513", Office: "Office of Energy & Transportation", IndustryTitle: "AIR COURIER SERVICES"}:                                             {},
	{Code: "4522", Office: "Office of Energy & Transportation", IndustryTitle: "AIR TRANSPORTATION, NONSCHEDULED"}:                                 {},
	{Code: "4581", Office: "Office of Energy & Transportation", IndustryTitle: "AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES"}:              {},
	{Code: "4610", Office: "Office of Energy & Transportation", IndustryTitle: "PIPE LINES (NO NATURAL GAS)"}:                                      {},
	{Code: "4700", Office: "Office of Energy & Transportation", IndustryTitle: "TRANSPORTATION SERVICES"}:                                          {},
	{Code: "4731", Office: "Office of Energy & Transportation", IndustryTitle: "ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO"}:                 {},
	{Code: "4812", Office: "Office of Technology", IndustryTitle: "RADIOTELEPHONE COMMUNICATIONS"}:                                                 {},
	{Code: "4813", Office: "Office of Technology", IndustryTitle: "TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)"}:                                  {},
	{Code: "4822", Office: "Office of Technology", IndustryTitle: "TELEGRAPH & OTHER MESSAGE COMMUNICATIONS"}:                                      {},
	{Code: "4832", Office: "Office of Technology", IndustryTitle: "RADIO BROADCASTING STATIONS"}:                                                   {},
	{Code: "4833", Office: "Office of Technology", IndustryTitle: "TELEVISION BROADCASTING STATIONS"}:                                              {},
	{Code: "4841", Office: "Office of Technology", IndustryTitle: "CABLE & OTHER PAY TELEVISION SERVICES"}:                                         {},
	{Code: "4899", Office: "Office of Technology", IndustryTitle: "COMMUNICATIONS SERVICES, NEC"}:                                                  {},
	{Code: "4900", Office: "Office of Energy & Transportation", IndustryTitle: "ELECTRIC, GAS & SANITARY SERVICES"}:                                {},
	{Code: "4911", Office: "Office of Energy & Transportation", IndustryTitle: "ELECTRIC SERVICES"}:                                                {},
	{Code: "4922", Office: "Office of Energy & Transportation", IndustryTitle: "NATURAL GAS TRANSMISSION"}:                                         {},
	{Code: "4923", Office: "Office of Energy & Transportation", IndustryTitle: "NATURAL GAS TRANSMISISON & DISTRIBUTION"}:                          {},
	{Code: "4924", Office: "Office of Energy & Transportation", IndustryTitle: "NATURAL GAS DISTRIBUTION"}:                                         {},
	{Code: "4931", Office: "Office of Energy & Transportation", IndustryTitle: "ELECTRIC & OTHER SERVICES COMBINED"}:                               {},
	{Code: "4932", Office: "Office of Energy & Transportation", IndustryTitle: "GAS & OTHER SERVICES COMBINED"}:                                    {},
	{Code: "4941", Office: "Office of Energy & Transportation", IndustryTitle: "WATER SUPPLY"}:                                                     {},
	{Code: "4950", Office: "Office of Energy & Transportation", IndustryTitle: "SANITARY SERVICES"}:                                                {},
	{Code: "4953", Office: "Office of Energy & Transportation", IndustryTitle: "REFUSE SYSTEMS"}:                                                   {},
	{Code: "4955", Office: "Office of Energy & Transportation", IndustryTitle: "HAZARDOUS WASTE MANAGEMENT"}:                                       {},
	{Code: "4961", Office: "Office of Energy & Transportation", IndustryTitle: "STEAM & AIR-CONDITIONING SUPPLY"}:                                  {},
	{Code: "4991", Office: "Office of Energy & Transportation", IndustryTitle: "COGENERATION SERVICES & SMALL POWER PRODUCERS"}:                    {},
	{Code: "5000", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-DURABLE GOODS"}:                                                 {},
	{Code: "5010", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES"}:               {},
	{Code: "5013", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS"}:                            {},
	{Code: "5020", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-FURNITURE & HOME FURNISHINGS"}:                                  {},
	{Code: "5030", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS"}:                         {},
	{Code: "5031", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS"}:                       {},
	{Code: "5040", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES"}:                {},
	{Code: "5045", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE"}:                   {},
	{Code: "5047", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES"}:               {},
	{Code: "5050", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-METALS & MINERALS (NO PETROLEUM)"}:                              {},
	{Code: "5051", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-METALS SERVICE CENTERS & OFFICES"}:                              {},
	{Code: "5063", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES"}:             {},
	{Code: "5064", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS"}:                        {},
	{Code: "5065", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC"}:                             {},
	{Code: "5070", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES"}:            {},
	{Code: "5072", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-HARDWARE"}:                                                      {},
	{Code: "5080", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES"}:                               {},
	{Code: "5082", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP"}:            {},
	{Code: "5084", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT"}:                              {},
	{Code: "5090", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MISC DURABLE GOODS"}:                                            {},
	{Code: "5094", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS"}:                    {},
	{Code: "5099", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-DURABLE GOODS, NEC"}:                                            {},
	{Code: "5110", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-PAPER & PAPER PRODUCTS"}:                                        {},
	{Code: "5122", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES"}:                    {},
	{Code: "5130", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-APPAREL, PIECE GOODS & NOTIONS"}:                                {},
	{Code: "5140", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-GROCERIES & RELATED PRODUCTS"}:                                  {},
	{Code: "5141", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-GROCERIES, GENERAL LINE"}:                                       {},
	{Code: "5150", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-FARM PRODUCT RAW MATERIALS"}:                                    {},
	{Code: "5160", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-CHEMICALS & ALLIED PRODUCTS"}:                                   {},
	{Code: "5171", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS"}:                           {},
	{Code: "5172", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)"}:             {},
	{Code: "5180", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES"}:                    {},
	{Code: "5190", Office: "Office of Trade & Services", IndustryTitle: "WHOLESALE-MISCELLANEOUS NONDURABLE GOODS"}:                                {},
	{Code: "5200", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY"}:                      {},
	{Code: "5211", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS"}:                        {},
	{Code: "5271", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-MOBILE HOME DEALERS"}:                                              {},
	{Code: "5311", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-DEPARTMENT STORES"}:                                                {},
	{Code: "5331", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-VARIETY STORES"}:                                                   {},
	{Code: "5399", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-MISC GENERAL MERCHANDISE STORES"}:                                  {},
	{Code: "5400", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-FOOD STORES"}:                                                      {},
	{Code: "5411", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-GROCERY STORES"}:                                                   {},
	{Code: "5412", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-CONVENIENCE STORES"}:                                               {},
	{Code: "5500", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-AUTO DEALERS & GASOLINE STATIONS"}:                                 {},
	{Code: "5531", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-AUTO & HOME SUPPLY STORES"}:                                        {},
	{Code: "5600", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-APPAREL & ACCESSORY STORES"}:                                       {},
	{Code: "5621", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-WOMEN'S CLOTHING STORES"}:                                          {},
	{Code: "5651", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-FAMILY CLOTHING STORES"}:                                           {},
	{Code: "5661", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-SHOE STORES"}:                                                      {},
	{Code: "5700", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES"}:                   {},
	{Code: "5712", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-FURNITURE STORES"}:                                                 {},
	{Code: "5731", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES"}:                          {},
	{Code: "5734", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-COMPUTER & COMPUTER SOFTWARE STORES"}:                              {},
	{Code: "5735", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-RECORD & PRERECORDED TAPE STORES"}:                                 {},
	{Code: "5810", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-EATING & DRINKING PLACES"}:                                         {},
	{Code: "5812", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-EATING PLACES"}:                                                    {},
	{Code: "5900", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-MISCELLANEOUS RETAIL"}:                                             {},
	{Code: "5912", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-DRUG STORES AND PROPRIETARY STORES"}:                               {},
	{Code: "5940", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-MISCELLANEOUS SHOPPING GOODS STORES"}:                              {},
	{Code: "5944", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-JEWELRY STORES"}:                                                   {},
	{Code: "5945", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-HOBBY, TOY & GAME SHOPS"}:                                          {},
	{Code: "5960", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-NONSTORE RETAILERS"}:                                               {},
	{Code: "5961", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-CATALOG & MAIL-ORDER HOUSES"}:                                      {},
	{Code: "5990", Office: "Office of Trade & Services", IndustryTitle: "RETAIL-RETAIL STORES, NEC"}:                                               {},
	{Code: "6021", Office: "Office of Finance", IndustryTitle: "NATIONAL COMMERCIAL BANKS"}:                                                        {},
	{Code: "6022", Office: "Office of Finance", IndustryTitle: "STATE COMMERCIAL BANKS"}:                                                           {},
	{Code: "6029", Office: "Office of Finance", IndustryTitle: "COMMERCIAL BANKS, NEC"}:                                                            {},
	{Code: "6035", Office: "Office of Finance", IndustryTitle: "SAVINGS INSTITUTION, FEDERALLY CHARTERED"}:                                         {},
	{Code: "6036", Office: "Office of Finance", IndustryTitle: "SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED"}:                                    {},
	{Code: "6099", Office: "Office of Finance", IndustryTitle: "FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC"}:                                     {},
	{Code: "6111", Office: "Office of Finance", IndustryTitle: "FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES"}:                                    {},
	{Code: "6141", Office: "Office of Finance", IndustryTitle: "PERSONAL CREDIT INSTITUTIONS"}:                                                     {},
	{Code: "6153", Office: "Office of Finance", IndustryTitle: "SHORT-TERM BUSINESS CREDIT INSTITUTIONS"}:                                          {},
	{Code: "6159", Office: "Office of Finance", IndustryTitle: "MISCELLANEOUS BUSINESS CREDIT INSTITUTION"}:                                        {},
	{Code: "6162", Office: "Office of Finance", IndustryTitle: "MORTGAGE BANKERS & LOAN CORRESPONDENTS"}:                                           {},
	{Code: "6163", Office: "Office of Finance", IndustryTitle: "LOAN BROKERS"}:                                                                     {},
	{Code: "6172", Office: "Office of Finance", IndustryTitle: "FINANCE LESSORS"}:                                                                  {},
	{Code: "6189", Office: "Office of Structured Finance", IndustryTitle: "ASSET-BACKED SECURITIES"}:                                               {},
	{Code: "6199", Office: "Office of Finance or Office of Crypto Assets", IndustryTitle: "FINANCE SERVICES"}:                                      {},
	{Code: "6200", Office: "Office of Crypto Assets", IndustryTitle: "SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES"}:                {},
	{Code: "6211", Office: "Office of Finance or\u00a0Office of Crypto Assets", IndustryTitle: "SECURITY BROKERS, DEALERS & FLOTATION COMPANIES"}:  {},
	{Code: "6221", Office: "Office of Crypto Assets", IndustryTitle: "COMMODITY CONTRACTS BROKERS & DEALERS"}:                                      {},
	{Code: "6282", Office: "Office of Finance", IndustryTitle: "INVESTMENT ADVICE"}:                                                                {},
	{Code: "6311", Office: "Office of Finance", IndustryTitle: "LIFE INSURANCE"}:                                                                   {},
	{Code: "6321", Office: "Office of Finance", IndustryTitle: "ACCIDENT & HEALTH INSURANCE"}:                                                      {},
	{Code: "6324", Office: "Office of Finance", IndustryTitle: "HOSPITAL & MEDICAL SERVICE PLANS"}:                                                 {},
	{Code: "6331", Office: "Office of Finance", IndustryTitle: "FIRE, MARINE & CASUALTY INSURANCE"}:                                                {},
	{Code: "6351", Office: "Office of Finance", IndustryTitle: "SURETY INSURANCE"}:                                                                 {},
	{Code: "6361", Office: "Office of Finance", IndustryTitle: "TITLE INSURANCE"}:                                                                  {},
	{Code: "6399", Office: "Office of Finance", IndustryTitle: "INSURANCE CARRIERS, NEC"}:                                                          {},
	{Code: "6411", Office: "Office of Finance", IndustryTitle: "INSURANCE AGENTS, BROKERS & SERVICE"}:                                              {},
	{Code: "6500", Office: "Office of Real Estate & Construction", IndustryTitle: "REAL ESTATE"}:                                                   {},
	{Code: "6510", Office: "Office of Real Estate & Construction", IndustryTitle: "REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS"}:               {},
	{Code: "6512", Office: "Office of Real Estate & Construction", IndustryTitle: "OPERATORS OF NONRESIDENTIAL BUILDINGS"}:                         {},
	{Code: "6513", Office: "Office of Real Estate & Construction", IndustryTitle: "OPERATORS OF APARTMENT BUILDINGS"}:                              {},
	{Code: "6519", Office: "Office of Real Estate & Construction", IndustryTitle: "LESSORS OF REAL PROPERTY, NEC"}:                                 {},
	{Code: "6531", Office: "Office of Real Estate & Construction", IndustryTitle: "REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)"}:                    {},
	{Code: "6532", Office: "Office of Real Estate & Construction", IndustryTitle: "REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)"}:                   {},
	{Code: "6552", Office: "Office of Real Estate & Construction", IndustryTitle: "LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)"}:                 {},
	{Code: "6770", Office: "Multiple Offices", IndustryTitle: "BLANK CHECKS"}:                                                                      {},
	{Code: "6792", Office: "Office of Energy & Transportation", IndustryTitle: "OIL ROYALTY TRADERS"}:                                              {},
	{Code: "6794", Office: "Office of Real Estate & Construction", IndustryTitle: "PATENT OWNERS & LESSORS"}:                                       {},
	{Code: "6795", Office: "Office of Energy & Transportation", IndustryTitle: "MINERAL ROYALTY TRADERS"}:                                          {},
	{Code: "6798", Office: "Office of Real Estate & Construction", IndustryTitle: "REAL ESTATE INVESTMENT TRUSTS"}:                                 {},
	{Code: "6799", Office: "Office of Real Estate & Construction", IndustryTitle: "INVESTORS, NEC"}:                                                {},
	{Code: "7000", Office: "Office of Real Estate & Construction", IndustryTitle: "HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES"}:          {},
	{Code: "7011", Office: "Office of Real Estate & Construction", IndustryTitle: "HOTELS & MOTELS"}:                                               {},
	{Code: "7200", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-PERSONAL SERVICES"}:                                              {},
	{Code: "7310", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ADVERTISING"}:                                                    {},
	{Code: "7311", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ADVERTISING AGENCIES"}:                                           {},
	{Code: "7320", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES"}:                 {},
	{Code: "7330", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY"}:            {},
	{Code: "7331", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-DIRECT MAIL ADVERTISING SERVICES"}:                               {},
	{Code: "7340", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-TO DWELLINGS & OTHER BUILDINGS"}:                                 {},
	{Code: "7350", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING"}:                       {},
	{Code: "7359", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-EQUIPMENT RENTAL & LEASING, NEC"}:                                {},
	{Code: "7361", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-EMPLOYMENT AGENCIES"}:                                            {},
	{Code: "7363", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-HELP SUPPLY SERVICES"}:                                           {},
	{Code: "7370", Office: "Office of Technology", IndustryTitle: "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC."}:                          {},
	{Code: "7371", Office: "Office of Technology", IndustryTitle: "SERVICES-COMPUTER PROGRAMMING SERVICES"}:                                        {},
	{Code: "7372", Office: "Office of Technology", IndustryTitle: "SERVICES-PREPACKAGED SOFTWARE"}:                                                 {},
	{Code: "7373", Office: "Office of Technology", IndustryTitle: "SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN"}:                                   {},
	{Code: "7374", Office: "Office of Technology", IndustryTitle: "SERVICES-COMPUTER PROCESSING & DATA PREPARATION"}:                               {},
	{Code: "7377", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-COMPUTER RENTAL & LEASING"}:                                      {},
	{Code: "7380", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MISCELLANEOUS BUSINESS SERVICES"}:                                {},
	{Code: "7381", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES"}:                        {},
	{Code: "7384", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-PHOTOFINISHING LABORATORIES"}:                                    {},
	{Code: "7385", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-TELEPHONE INTERCONNECT SYSTEMS"}:                                 {},
	{Code: "7389", Office: "Office of Trade & Services or Office of Energy & Transportation", IndustryTitle: "SERVICES-BUSINESS SERVICES, NEC"}:    {},
	{Code: "7500", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING"}:                          {},
	{Code: "7510", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)"}:                             {},
	{Code: "7600", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MISCELLANEOUS REPAIR SERVICES"}:                                  {},
	{Code: "7812", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION"}:                         {},
	{Code: "7819", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ALLIED TO MOTION PICTURE PRODUCTION"}:                            {},
	{Code: "7822", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION"}:                       {},
	{Code: "7829", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION"}:                          {},
	{Code: "7830", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MOTION PICTURE THEATERS"}:                                        {},
	{Code: "7841", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-VIDEO TAPE RENTAL"}:                                              {},
	{Code: "7900", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-AMUSEMENT & RECREATION SERVICES"}:                                {},
	{Code: "7948", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-RACING, INCLUDING TRACK OPERATION"}:                              {},
	{Code: "7990", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION"}:                           {},
	{Code: "7997", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS"}:                           {},
	{Code: "8000", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-HEALTH SERVICES"}:                                      {},
	{Code: "8011", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE"}:             {},
	{Code: "8050", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-NURSING & PERSONAL CARE FACILITIES"}:                   {},
	{Code: "8051", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-SKILLED NURSING CARE FACILITIES"}:                      {},
	{Code: "8060", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-HOSPITALS"}:                                            {},
	{Code: "8062", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC"}:            {},
	{Code: "8071", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-MEDICAL LABORATORIES"}:                                 {},
	{Code: "8082", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-HOME HEALTH CARE SERVICES"}:                            {},
	{Code: "8090", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-MISC HEALTH & ALLIED SERVICES, NEC"}:                   {},
	{Code: "8093", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC"}:                 {},
	{Code: "8111", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-LEGAL SERVICES"}:                                                 {},
	{Code: "8200", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-EDUCATIONAL SERVICES"}:                                           {},
	{Code: "8300", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-SOCIAL SERVICES"}:                                      {},
	{Code: "8351", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-CHILD DAY CARE SERVICES"}:                                        {},
	{Code: "8600", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MEMBERSHIP ORGANIZATIONS"}:                                       {},
	{Code: "8700", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT"}:                  {},
	{Code: "8711", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-ENGINEERING SERVICES"}:                                           {},
	{Code: "8731", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH"}:            {},
	{Code: "8734", Office: "Industrial Applications and Services", IndustryTitle: "SERVICES-TESTING LABORATORIES"}:                                 {},
	{Code: "8741", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MANAGEMENT SERVICES"}:                                            {},
	{Code: "8742", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-MANAGEMENT CONSULTING SERVICES"}:                                 {},
	{Code: "8744", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES"}:                         {},
	{Code: "8880", Office: "Office of International Corp Fin", IndustryTitle: "AMERICAN DEPOSITARY RECEIPTS"}:                                      {},
	{Code: "8888", Office: "Office of International Corp Fin", IndustryTitle: "FOREIGN GOVERNMENTS"}:                                               {},
	{Code: "8900", Office: "Office of Trade & Services", IndustryTitle: "SERVICES-SERVICES, NEC"}:                                                  {},
	{Code: "9721", Office: "Office of International Corp Fin", IndustryTitle: "INTERNATIONAL AFFAIRS"}:                                             {},
	{Code: "9995", Office: "Office of Real Estate & Construction", IndustryTitle: "NON-OPERATING ESTABLISHMENTS"}:                                  {},
}
